version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: test_db
      MYSQL_USER: po3rin
      MYSQL_PASSWORD: 1234567890
      TZ: "Asia/Tokyo"
    restart: always
    tty: true